/* Gerado a partir da classificação revisada das questões CAP. */
export const chapterAssignments: Record<string, string> = {
  "¿cuántos vocales debe tener una junta arbitral de transporte?": "goods-2-2",
  "el convenio cmr se aplicará a los contratos de transporte de mercancías por carretera en los que:": "goods-2-2",
  "en el transporte de paquetería, la colocación y estiba de las mercancías en el vehículo serán por cuenta:": "goods-1-4",
  "la norma de que los conductores de vehículos de transporte de mercancías con mma superior a 7,5 toneladas no deben participar, salvo excepciones, en las operaciones de carga del vehículo:": "goods-1-4",
  "¿cómo se denomina el transporte efectuado a través de un país sin tomar ni dejar mercancías en el mismo?": "goods-2-2",
  "(reserva 6º) ¿qué riesgo principal presenta la clase 8 de mercancías peligrosas?": "goods-1-4",
  "cuando en un transporte sujeto al convenio cmr se utilice la carta de porte electrónica, el remitente podrá comunicar de forma electrónica al transportista:": "goods-2-2",
  "(reserva 5º) ¿cómo se debe señalizar un vehículo que transporta mercancías peligrosas durante la noche?": "goods-1-4",
  "dentro de los sistemas de transporte inteligente se encuentran los denominados v2v, ¿cuál es su funcionalidad característica?": "common-1-2",
  "¿qué conductores de vehículos de transporte de mercancías deben llevar a bordo su tarjeta de cualificación profesional?": "common-2-1",
  "el tipo de esfuerzo requerido para el manejo de la carga del vehículo influye en el nivel de riesgo. así, es más segura la manipulación que exija:": "common-3-3",
  "en el caso de un transporte efectuado en régimen de tránsito de la unión, ¿qué se debe presentar en las aduanas de tránsito?": "goods-2-2",
  "¿cuántos viajes, como máximo, se pueden hacer con una autorización cemt?": "goods-2-2",
  "¿qué aspectos debe cuidar básicamente una empresa de transporte en sus instalaciones?": "common-3-6",
  "según el reglamento (ce) 1/2005, relativo a la protección de los animales durante su transporte, los terneros menores de 10 días no son aptos para el transporte, salvo que el viaje sea inferior a:": "goods-2-2",
  "la responsabilidad del transportista por pérdida de mercancías:": "goods-2-2",
  "de acuerdo con la clasificación de las mercancías peligrosas que hace el adr, ¿a qué clase de mercancía hace referencia la clase 7?": "goods-1-4",
  "(reserva 1º) las cargas formadas por bloques pesados o muy pesados, ¿en qué parte de la batea deben colocarse?": "goods-1-4",
  "¿cuál de los siguientes transportes internacionales de mercancías entre países integrados en el sistema de autorizaciones cemt está liberalizado?": "goods-2-2",
  "en el transporte internacional, ¿a qué se denomina operaciones triangulares?": "goods-2-2",
  "la licencia comunitaria para transporte de mercancías es:": "goods-2-2",
  "si un consumidor opta por contratar un seguro que cubra los daños que puedan sufrir las mercancías durante el transporte, ¿quién debe asumir su coste?": "goods-2-2",
  "¿qué ocurre si la parte reclamada no acude a la vista celebrada ante una junta arbitral del transporte?": "goods-2-2",
  "¿cuál es el plazo para la presentación de reclamaciones por daños aparentes en la mercancía según el cmr?": "goods-2-2",
  "¿qué variables existen para definir el tráfico existente en una carretera?": "common-1-3bis",
  "¿cuál de las siguientes circunstancias aumenta el consumo de carburante?": "common-1-3",
  "el dispositivo de seguridad bas, ¿qué acción lleva a cabo?": "common-1-2",
  "¿cómo puede definirse la \"circulación discontinua\"?": "common-1-3bis",
  "(reserva 32º) el conductor de un vehículo, ¿puede realizar maniobras marcha atrás?": "common-1-3bis",
  "en los motores de los automóviles actuales, si el vehículo circula a más de $20~km/h$, no se pisa el pedal del embrague ni del acelerador y hay engranada una velocidad en la caja de cambios, el consumo:": "common-1-3",
  "¿cuántos puntos pierde en el permiso de conducir un conductor que haya colaborado en la manipulación del tacógrafo?": "common-2-1",
  "¿cuál de estos es un factor de riesgo?": "common-3-1",
  "¿qué se entiende por grupos de riesgo en seguridad vial?": "common-3-1",
  "¿quién debe entregar la declaración amistosa de accidente?": "common-3-5",
  "(reserva 9º) ¿en qué documento se anotan las sanciones graves?": "common-2-1",
  "de los que se indican a continuación, ¿qué elemento pertenece al sistema de transmisión de un automóvil?": "common-1-1",
  "¿a qué administración se debe comunicar la realización de un curso que se va a impartir en una sucursal ubicada en una comunidad autónoma distinta de la que otorgó la autorización de empresa cap?": "common-2-1",
  "¿cómo define la \"pausa\" el reglamento (ce) 561/2006?": "common-2-1",
  "(reserva 19º) la presión correcta de los neumáticos:": "common-3-6",
  "(reserva 7º) ¿cuál es el objetivo de los tacógrafos?": "common-2-1",
  "¿qué circunstancias pueden influir negativamente en la percepción del riesgo del conductor?": "common-3-4",
  "¿a qué administración se debe imputar la infracción por no respetar el tiempo de descanso diario, que a su vez represente una falta muy grave de indisciplina del conductor respecto de las instrucciones recibidas de la empresa, si este es objeto de una sanción disciplinaria por la misma consistente en suspensión de empleo y sueldo y no la recurre judicialmente?": "common-2-1",
  "según el círculo de kamm, si la fuerza total equivale a la fuerza de frenado:": "common-1-2",
  "¿qué se entiende por conductor profesional?": "common-2-1",
  "el capital social de una sociedad anónima debe estar desembolsado, por lo menos, en un:": "goods-3-7",
  "al trabajar sentado, ¿cómo debe ser la posición?": "common-3-3",
  "(reserva 21º) las luces de posición sirven para:": "common-1-2",
  "los embragues hidráulicos son:": "common-1-1",
  "101 (reserva 1º). el semirremolque:": "common-1-1",
  "en el cuentarrevoluciones de un vehículo pesado existe una zona marcada, generalmente, de color verde, ¿qué indica?": "common-1-1",
  "¿qué debe hacerse con los restos de ropa quemada a un herido de accidente de tráfico?": "common-3-5",
  "¿qué intentan conservar los pares de las ruedas y los pares de inercia que intervienen en un camión?": "common-1-1",
  "¿qué automóviles carecen de árbol de transmisión?": "common-1-1",
  "salvo que el fabricante del vehículo considere otro mantenimiento diferente, ¿cada cuántos kilómetros es conveniente cambiar actualmente los aceites minerales en motores diésel?": "common-3-6",
  "la ergonomía busca incrementar en el ámbito del trabajo:": "common-3-3",
  "¿qué se debe usar antes: los retardadores hidráulicos o el freno de servicio?": "common-1-2",
  "para evitar los problemas de salud que produce el trabajo sedentario, es recomendable cambiar de postura al menos cada:": "common-3-3",
  "¿qué se consigue con el sistema eds (electronic differential system)?": "common-1-2",
  "¿cómo se denomina también el método de las preferencias declaradas, utilizado para valorar económicamente los costes humanos de los accidentes de tráfico?": "common-3-1",
  "(reserva 29º) ¿se debe utilizar el cinturón de seguridad en el asiento trasero?": "common-1-3bis",
  "¿qué indica una luz de emergencia?": "common-1-2",
  "en una caja de velocidades con 5 marchas, ¿qué se consigue con la quinta velocidad?": "common-1-1",
  "un conductor que conduce en una semana 52 horas, ¿cuántas horas puede conducir, como máximo, la semana siguiente, según la reglamentación social europea?": "common-2-1",
  "¿qué vehículo está obligado a usar tacógrafo?": "common-2-1",
  "de acuerdo con la ley de cooperativas, los socios que pidan la celebración de una asamblea extraordinaria podrán instar al juez competente que la convoque si el consejo rector no ha atendido su requerimiento en el plazo de:": "goods-3-7",
  "¿cuál de los siguientes comportamientos se puede utilizar para disminuir el nivel de alcohol en sangre?": "common-3-4",
  "¿cuál es el ámbito de aplicación del espacio schengen?": "goods-2-2",
  "¿qué es una glorieta?": "common-1-3bis",
  "cuando en la inspección de un curso cap se compruebe que la materia impartida no coincide con la que ha sido comunicada:": "common-2-1",
  "en el transcurso de dos semanas consecutivas, el conductor tendrá que tomar:": "common-2-1",
  "(reserva 30º) ¿qué es el aquaplaning?": "common-1-3bis",
  "¿qué son los \"accidentes con forma no traumática\"?": "common-3-1",
  "la valvulina...": "common-1-1",
  "¿qué se entiende por trayectoria real del camión más abierta de la que debería realizar?": "common-1-3bis",
  "¿en qué momento se produce el deslizamiento de un neumático?": "common-1-3bis",
  "¿qué características van a definir en el cuentarrevoluciones de un automóvil la zona económica del motor?": "common-1-1",
  "(reserva 17º) en caso de colisión, el cinturón de seguridad:": "common-1-2",
  "el consumo específico de un motor, ¿indica cómo es su rendimiento?": "common-1-3",
  "¿qué es una vía preferente?": "common-1-3bis",
  "¿qué funciones corporales aumentan de día y disminuyen de noche?": "common-3-4",
  "el chasis deformable es un elemento de seguridad...": "common-1-2",
  "¿qué problemas de salud suele dar el trabajo sedentario?": "common-3-3",
  "¿cuál de estas afirmaciones es falsa?": "common-3-4",
  "de las siguientes fuerzas, ¿cuál interviene principalmente en el movimiento de un camión?": "common-1-1",
  "¿se debe mantener distancia de seguridad?": "common-1-3bis",
  "el centro que haya limpiado un vehículo que transportó animales:": "goods-2-2",
  "para evitar el atropello de ciclistas, debe tenerse en cuenta que:": "common-1-3bis",
  "¿cuántas veces se podrá interrumpir, para llevar a cabo otras actividades, el período de descanso diario normal cuando se acompañe un vehículo transportado por trasbordador o tren?": "common-2-1",
  "cuantos menos cambios de marcha realice el conductor de un camión durante una subida:": "common-1-3",
  "en función de por dónde se circule, se recomiendan unas técnicas indicadas para optimizar el consumo de carburante. ¿qué se recomienda en llano?": "common-1-3",
  "¿de qué forma se identifica un usuario con el tacógrafo digital?": "common-2-1",
  "se puede considerar como accidentes de trabajo con forma no traumática a:": "common-3-1",
  "¿cómo se llaman los símbolos que aparecen en determinados mensajes de la pantalla del tacógrafo digital?": "common-2-1",
  "circular con un neumático con la presión de inflado inferior a la recomendada por el fabricante hace que aumente el consumo de carburante porque:": "common-1-3",
  "(reserva 4º) ¿qué es una caja de cambios de toma constante?": "common-1-1",
  "¿cuáles son los factores de riesgo en la conducción?": "common-1-3bis",
  "a medida que aumenta la velocidad, el camión tiene que desplazar:": "common-1-3",
  "¿qué sucede en caso de avería o mal funcionamiento del tacógrafo?": "common-2-1",
  "¿la carencia de autorización de transporte puede dar lugar a la inmovilización de un autobús?": "goods-2-2",
  "en un contrato de transporte sujeto al convenio cmr, ¿qué indicaciones debe contener la carta de porte?": "goods-2-2",
  "la norma de que los conductores de vehículos de transporte de mercancías con mma superior a 7,5 toneladas no pueden participar en las operaciones de descarga del vehículo no se aplica en el caso de:": "goods-1-4",
  "según la normativa laboral española, ¿quién tiene la consideración de trabajador móvil en una empresa de transporte por carretera?": "common-2-1",
  "salvo de prueba en contrario, ¿cuál de los siguientes se considerará precio usual de un servicio de transporte?": "goods-2-2",
  "¿pueden los estados firmantes del convenio cmr adoptar acuerdos particulares entre ellos que resulten contrarios al mismo?": "goods-2-2",
  "en comparación con el resto de vehículos, ¿qué nivel alcanza la intervención de los autobuses y vehículos de transporte de mercancías en accidentes de tráfico si se tienen en cuenta los kilómetros recorridos?": "common-3-1",
  "en el caso de un transporte efectuado en régimen de tránsito comunitario, ¿cómo se determina el itinerario del viaje?": "goods-2-2",
  "en un contrato de transporte sujeto al convenio cmr que es ejecutado por varios transportistas de modo sucesivo, el transportista que haya pagado una indemnización:": "goods-2-2",
  "¿qué requisitos, de entre los siguientes, son necesarios para obtener autorización de transporte público de mercancías en vehículos con mma superior a 3,5 toneladas?": "goods-2-2",
  "una vez apartado el vehículo y señalizado el obstáculo, ¿cuál es la siguiente medida que deberá adoptar el conductor de un vehículo cuya carga se haya caído sobre la vía?": "common-3-5",
  "en un contrato de transporte sujeto al convenio cmr, ¿está limitada la responsabilidad del transportista por pérdida de la mercancía?": "goods-2-2",
  "¿quién de los siguientes puede desarrollar legalmente funciones de mediación entre las empresas cargadoras y los transportistas?": "goods-2-2",
  "según el reglamento (ce) 1/2005, relativo a la protección de los animales durante su transporte, se considera viaje largo aquel que tiene una duración superior a:": "goods-2-2",
  "el transporte de mercancías que no sobrepasa los límites de un país se conoce con el nombre de transporte:": "goods-2-2",
  "¿qué se entiende por \"transporte por cuenta propia\"?": "goods-2-2",
  "¿cuáles son las funciones propias del gerente de una empresa de transporte de mercancías por carretera?": "goods-3-7",
  "en el ámbito del transporte de mercancías, la carretera es, en valores absolutos, la principal fuente de emisiones de:": "goods-3-7",
  "en relación con el documento de control administrativo de transporte de mercancías, ¿qué datos debe introducir el conductor?": "goods-2-2",
  "una de las restricciones que pueden presentar las autorizaciones cemt es:": "goods-2-2",
  "en un transporte, ante las sospechas de falsedad en la declaración del contenido, ¿qué puede hacer el porteador?": "goods-2-2",
  "¿qué es el \"efecto túnel\"?": "common-1-3bis",
  "¿cuál es el prazo de prescripción de las sanciones por infracciones muy graves de las normas relativas a los tiempos de conducción y descanso?": "common-2-1",
  "¿qué zapatos son adecuados para trabajar de pie?": "common-3-3",
  "¿dónde se deben ubicar los diferentes mandos del vehículo?": "common-3-3",
  "en caso de avería o mal funcionamiento del tacógrafo digital, el conductor:": "common-2-1",
  "en un motor de combustión, el par motor, ¿está relacionado con el consumo de carburante?": "common-1-1",
  "en una sociedad anónima, el capital social no puede ser nunca inferior a:": "goods-3-7",
  "¿por qué es importante el dispositivo abs?": "common-1-2",
  "salvo pacto previo de sumisión a una junta concreta, ¿qué junta arbitral puede elegir el demandante para la resolución de una controversia?": "goods-2-2",
  "entre las medidas preventivas para una conducción segura está:": "common-1-3bis",
  "¿cómo se denomina la pauta de actuación ante emergencias que se desarrolla en las fases de proteger a las personas y el lugar del siniestro, alertar a los servicios de auxilio y socorrer a los heridos?": "common-3-5",
  "¿puede un estado de la unión europea imponer sanciones por infracciones de los tiempos de conducción y descanso cometidas en territorio de otro estado?": "common-2-1",
  "un vehículo no específicamente destinado al servicio de auxilio en vía pública, ¿puede efectuar en algún caso la retirada de la vía de otro vehículo averiado?": "common-1-3bis",
  "el instituto nacional de seguridad e higiene en el trabajo recomienda que, para el levantamiento de pesos manualmente en posición sentado, no se superen:": "common-3-3",
  "el deslizamiento de las ruedas motrices de un camión puede darse:": "common-1-1",
  "¿cuál es el periodo de vigencia de la tarjeta de cualificación expedida junto al certificado de aptitud profesional (cap), una vez se ha superado el examen de cualificación inicial?": "common-2-1",
  "el exceso de velocidad es:": "common-1-3bis",
  "¿cuál es el objetivo principal de los sistemas de contención de vehículos de una carretera?": "common-1-3bis",
  "para la obtención del permiso de conducir:": "common-2-1",
  "¿en qué casos puede elegir junta arbitral el demandado para la resolución de una controversia?": "goods-2-2",
  "son equipos de protección individual de la cabeza:": "common-3-3",
  "el uso de la baca en un automóvil:": "common-1-3",
  "(reserva 24º) los espejos retrovisores deben ajustarse:": "common-3-3",
  "¿qué influencia puede tener la polimedicación sobre la conducción de vehículos?": "common-3-4",
  "¿tiene que aparecer impreso en un disco-diagrama u hoja de registro el límite superior de velocidad que se puede registrar en el mismo?": "common-2-1",
  "la potencia de un motor:": "common-1-1",
  "para la renovación del permiso de conducir:": "common-2-1",
  "¿quién puede efectuar las operaciones de verificación trimestral de un extintor?": "common-3-5",
  "¿qué regula la orden de 27 de julio de 1999, sobre condiciones que deben reunir determinados extintores de incendios?": "common-3-5",
  "en caso de auxiliar en un accidente de tráfico, si algún airbag de los vehículos accidentados no se ha activado:": "common-3-5",
  "cuando existan condiciones meteorológicas o ambientales que disminuyan la visibilidad, como en caso de niebla, deberá utilizarse:": "common-1-3bis",
  "(reserva 11º) ¿cuál es la finalidad de la formación continua cap?": "common-2-1",
  "¿cómo pueden crearse las sociedades anónimas?": "goods-3-7",
  "¿cuál es el documento obligatorio del vehículo?": "common-2-1",
  "en pendientes ascendentes, se debe:": "common-1-3bis",
  "¿cómo se define la deceleración de un camión?": "common-1-2",
  "¿cuáles son las características que mejor describen las prestaciones de un motor?": "common-1-1",
  "¿la retardador hidráulico es compatible con el sistema abs de frenos?": "common-1-2",
  "¿qué acciones hay que realizar para conducir con seguridad?": "common-1-3bis",
  "(reserva 2º) ¿en qué se basa el funcionamiento del dispositivo denominado bas?": "common-1-2",
  "la fuerza que opone resistencia al movimiento entre la superficie de los neumáticos de un camión y la calzada se denomina:": "common-1-1",
  "a la hora de elegir un menú en carretera, es conveniente:": "common-3-4",
  "en caso de sufrir estrés, se aconseja:": "common-3-4",
  "¿de qué color será el fondo de las señales de identificación de una carretera autonómica de primer nivel?": "common-1-3bis",
  "¿qué es el \"aquaplaning\"?": "common-1-3bis",
  "¿qué tipo de control de una empresa cap debe realizar la administración que la autorizó?": "goods-3-7",
  "cada vez que se realiza un cambio durante la subida de una pendiente, existe un instante en el que el camión pierde potencia. ¿en qué se traducen estas pérdidas de potencia?": "common-1-1",
  "¿qué se debe evitar colocar en el espacio de conducción?": "common-3-3",
  "¿qué ocurre si la velocidad de giro de la rueda no coincide con la velocidad lineal del camión?": "common-1-2",
  "el consumo de carburante es mayor:": "common-1-3",
  "el consumo de carburante:": "common-1-3",
  "en un embrague de fricción en seco, el disco de embrague se encuentra situado...": "common-1-1",
  "(reserva 12º) ¿cómo debe ser el alumbrado en caso de lluvia intensa?": "common-1-3bis",
  "las marcas amarillas en zigzag, ¿para qué se utilizan?": "common-1-3bis",
  "¿qué puede ocurrir si el conductor presta atención a todos los estímulos que recibe durante la conducción?": "common-3-4",
  "¿cuál de los siguientes es un factor de riesgo para la conducción?": "common-3-4",
  "desde el punto de vista de su transporte material, las cargas pueden dividirse en:": "goods-1-4",
  "para el transporte de mercancías entre los países de la unión europea y los pertenecientes a la asociación europea de libre comercio, ¿cuál es el sistema de tránsito aduanero utilizado?": "goods-2-2",
  "la garantía exigida en el caso de transportes efectuados en régimen de tránsito de la unión será:": "goods-2-2",
  "¿qué entienden por carga indivisible las normas de circulación?": "goods-1-4",
  "¿cuándo se debe hace la limpieza de un vehículo que se dedica al transporte de productos alimenticios?": "goods-1-4",
  "¿are habituales los acuerdos de comercialización estables en el ámbito del transporte de mercancías por carretera?": "goods-3-7",
  "¿quién debe asumir el coste de los arbitrajes efectuados por una junta arbitral de transporte?": "goods-3-7",
  "¿cuántos extintores debe llevar un vehículo de transporte de mercancías de 6.000 kg de masa máxima autorizada (mma)?": "goods-2-2",
  "en un contrato de transporte sujeto al convenio cmr que es ejecutado por varios transportistas de modo sucesivo, ¿qué responsabilidad asume cada uno de ellos?": "goods-2-2",
  "el conductor de un vehículo pesado de transporte de mercancías:": "common-2-1",
  "el sistema que posee un motor de combustión encargado de controlar la apertura y el cierre de los orificios de admisión y de escape del cilindro se llama:": "common-1-1",
  "¿qué se quiere significar, en el marco de un modelo de gestión de la calidad, al decir que un servicio de transporte se caracteriza por su inseparabilidad?": "common-3-6",
  "cuando se realiza un transporte de mercancías en estado liquido en una cisterna, el movimiento de la carga afecta:": "goods-1-4",
  "en el caso de un transporte efectuado al amparo de una autorización cemt, ¿qué documento relativo a dicha autorización se habrá de llevar a bordo del vehículo?": "goods-2-2",
  "¿en qué condiciones los alumnos que realicen un curso para la obtención de la cualificación inicial de conductores podrán contabilizar como parte de dicha formación la realizada en relación con transporte de animales?": "goods-3-7",
  "el vehículo jaula es el normalmente utilizado en transporte de:": "goods-1-4",
  "(reserva 18º) ¿a qué se denomina punto muerto?": "common-1-1",
  "en caso de auxiliar en un accidente de tráfico:": "common-3-5",
  "entre los elementos internos que utiliza el conductor para su toma de decisiones durante la conducción se incluye:": "common-3-4",
  "¿qué documento no es obligatorio llevar a bordo del vehículo?": "common-2-1",
  "¿cuáles son los límites del régimen de revoluciones de un motor de combustión?": "common-1-1",
  "según la ley de responsabilidad civil y seguro en la circulación de vehículos a motor, ¿a qué dará lugar el incumplimiento de la obligación de asegurarse?": "common-2-1",
  "¿se puede circular marcha atrás?": "common-1-3bis",
  "¿pueden los agentes de control obligar a trasladar un vehículo a un taller autorizado en sentido contrario a su marcha?": "common-1-3bis",
  "la evaluación correcta de una situación de emrgencia permite:": "common-3-5",
  "¿qué es el llamado círculo de kamm?": "common-1-1",
  "¿a quién se imputará la infracción consistente en uso indebido del tacógrafo por un conductor, que a su vez represente una falta muy grave de indisciplina respecto de las instrucciones recibidas de la empresa, si el conductor no es objeto de sanción disciplinaria por la misma?": "common-2-1",
  "si en un control de carretera se detecta una falta de descanso diario considerada grave, ¿qué deberán hacer os agentes?": "common-2-1",
  "¿qué resistencias intervienen en el movimiento de los vehículos?": "common-1-1",
  "los medicamentos que pueden disminuir las capacidades necesarias para la conducción lo indicarán:": "common-3-4",
  "la señal de un vehículo consistente en una forma elíptica de fondo blanco y la letra e en negro, ¿qué indica?": "common-1-2",
  "¿qué debe tenerse en cuenta en frenadas de emergencia durante los descensos?": "common-1-2",
  "¿qué finalidad se persigue con el certificado cites?": "goods-2-2",
  "durante la conducción de un camión, ¿qué es la acelaración?": "common-1-1",
  "para comprobar el nivel de aceite en el cárter, ¿cómo debe estar estacionado el vehículo?": "common-3-6",
  "señale la afirmación correcta:": "common-3-6",
  "¿qué es el \"efecto tijera\"?": "common-1-2",
  "¿qué haremos para prevenir la aparición de sueño durante la conducción?": "common-3-4",
  "entre otras, ¿qué característica va a definir en el cuentarrevoluciones de un automóvil la zona económica del motor?": "common-1-1",
  "¿cómo se llama a la energía que tiene un vehículo en movimento?": "common-1-1",
  "(reserva 23º) el uso del móvil al volante:": "common-3-1",
  "los ciclos del ritmo circadiano tienen una duración de en torno a:": "common-3-4",
  "¿cuál de las siguientes afirmaciones sobre la hoja de registro o discos-diagrama del tacógrafo es verdadera?": "common-2-1",
  "¿puede el tacógrafo digital registrar la velocidad y la distancia recorrida al vehículo?": "common-2-1",
  "una disminución de tres horas y media en el descanso semanal, ¿qué tipo de infracción se considera?": "common-2-1",
  "la velocidad máxima en autopista para un camión es:": "common-1-3bis",
  "la responsabilidad de un conductor por colaborar en la introducción en españa de inmigrantes ilegales mediante el vehículo que tiene a su cargo se determina:": "common-3-2",
  "en el ámbito de la unión europea un vehículo articulado cuya cabeza tractora esté matriculada en un país y el semirremolque en otro...": "goods-2-2",
  "el aparato de control ayuda a...": "common-3-6",
  "en caso de tormenta con gran aparato eléctrico, ¿qué debemos hacer?": "common-1-3bis",
  "la aplicación de los conocimientos ergonómicos al ámbito del trabajo es fundamental para:": "common-3-3",
  "según el acuerdo atp, si el vehículo está dotado de un dispositivo térmico amovible o no autónomo, la marca o marcas de identificación se complementarán con la letra:": "goods-2-2",
  "el acuerdo atp se aplica:": "goods-2-2",
  "se denomina \"aceleración\" a la magnitud física que mide la variación:": "common-1-1",
  "¿cuál de las siguientes medidas de prevención de riesgos laborales es obligación del trabajador?": "common-3-3",
  "¿a qué régimen de revoluciones del motor de un vehículo es mayor el par motor?": "common-1-1",
  "(reserva 27º) ante una señal de ceda el paso:": "common-1-3bis",
  "de los siguientes factores, ¿cuál influye en el grado de rozamiento?": "common-1-1",
  "102 (reserva 2º). ¿qué sistema evita que patinen las ruedas motrices en el momento de acelerar?": "common-1-2",
  "¿cuál es una característica de la batería de litio de un vehículo eléctrico?": "common-3-6",
  "¿qué efecto produce sobre el vehículo una rueda bloqueada?": "common-1-2",
  "la banda de rodamiento de un neumático es la zona de la cubierta...": "common-3-6",
  "(reserva 3º) durante la conducción, el conductor recibe información en la que basa sus decisiones, ¿de dónde procede esa información?": "common-1-3bis",
  "¿en qué registro público oficial se anota la expedición del certificado de aptitud profesional?": "common-2-1",
  "para obtener el estatuto de operador económico autorizado se requiere:": "goods-2-2",
  "en un control en carretera, ¿debe el conductor permitir la inspección de la instalación del tacógrafo?": "common-2-1",
  "¿cuál de estas afirmaciones es incorrecta?": "common-3-6",
  "el protocolo de actuación ante emergencias que se desarrolla en las fases de proteger, avisar y socorrer se conoce como:": "common-3-5",
  "en los motores de los automóviles actuales, cuando el vehículo circula, no se pisa el pedal del acelerador ni del embrague y la palanca del cambio se encuentra en punto muerto:": "common-1-1",
  "las juntas arbitrales del transporte ejercen sus funciones en relación con:": "goods-2-2",
  "según el reglamento (ce) 1/2005, relativo a la protección de los animals durante su transporte, se considera viaje largo aquel que tiene una duración superior a:": "goods-2-2",
  "¿cuál de los siguientes es uno de los riesgos principales de la actividad del transporte?": "common-3-1",
  "los vehículos oficiales de transporte de mercancías que utilizan los órganos de la administración:": "goods-2-2",
  "en un contrato de transporte sujeto al convenio cmr, el derecho de disposición sobre la mercancía corresponde:": "goods-2-2",
  "¿cuál es el plazo máximo de reexportación de una mercancía importada al amparo de un cuaderno ata?": "goods-2-2",
  "según las condiciones generales de contratación en un contrato de transporte de mercancías, si el plazo de entrega al destinatario finaliza después de las seis de la tarde, ¿cuándo, como máximo, debe efectuarse dicha entrega?": "goods-2-2",
  "en un contrato de transporte sujeto al convenio cmr, ¿qué factores se tienen en cuenta para determinar el importe de la indemnización por pérdida de la mercancía?": "goods-2-2",
  "¿qué transportes de mercancías peligrosas están exentos de la utilización obligatoria de la rimp?": "goods-2-2",
  "el transporte de alimentos perecederos a temperatura regulada, ¿por qué acuerdo se rige fundamentalmente?": "goods-2-2",
  "¿cuáles de los siguientes accidentes de trabajo en el sector del transporte están considerados como accidentes con forma no traumática?": "common-3-1",
  "el titular de una autorización de transporte público de mercancías podrá sustituir alguno de los vehículos adscritos a la autorización si:": "goods-2-2",
  "en las estadísticas de accidentes de trabajo se observa que la incidencia y gravedad de los accidentes en el sector del transporte es:": "common-3-1",
  "según la ley de responsabilidad civil y seguro en la circulación de vehículo a motor, los daños en la mercancía transportada en el vehículo responsable del accidente:": "goods-2-2",
  "¿qué se considera transporte internacional de mercancías por carretera?": "goods-2-2",
  "¿qué clase de vehículos dedicados al transporte terrestre participa en menos accidentes de tráfico?": "common-3-1",
  "¿a qué transportes se aplica el convenio cmr?": "goods-2-2",
  "¿cuántos vocales deben formar parte de las juntas arbitrales del transporte?": "goods-2-2",
  "¿en cuánto se debe sobrepasar la velocidad permitida en una vía interurbana para que dicha conducta se considere delito contra la seguridad vial?": "goods-2-2",
  "para evitar los problemas de salud que produce el trabalho sedentario, es recomendado cambiar de postura al menos cada:": "common-3-3",
  "¿en cuál de los siguientes supuestos se puede utilizar un cuaderno ata?": "goods-2-2",
  "¿qué problemas puede dar un aceite de viscosidad demasiado baja?": "common-1-1",
  "¿cuál es la materia más empleada para extinguir un incendio por enfriamiento de la temperatura?": "common-3-5",
  "¿cuándo debe utilizarse el alumbrado del vehículo como regla general?": "common-1-3bis",
  "¿cuántos discos-diagrama tiene obligación de entregar el empresario a los conductores?": "common-2-1",
  "¿quiénes deben firmar la declaración amistosa de accidente para que se considere válida?": "common-3-5",
  "¿qué recomendación respecto de la conducción se debe efectuar a quien vaya a tomar un medicamento de categoría 0?": "common-3-4",
  "¿qué debe contener una carta de porte?": "goods-2-2",
  "¿cuándo se produce la resistencia a la aceleración?": "common-1-1",
  "la fuerza que opone resistencia al movimiento entre la superficie del neumático de un camión y la calzada se denomina:": "common-1-1",
  "¿se deben usar luces en caso de lluvia?": "common-1-3bis",
  "no necesitan certificado de aptitud profesional los conductores de vehículos cuya velocidad máxima sea:": "common-2-1",
  "¿qué medicamentos nos pueden producir somnolencia?": "common-3-4",
  "(reserva 13º) el conductor debe llevar la tarjeta de cualificación profesional:": "common-2-1",
  "la oms en su informe de 2004 define la ayuda a las víctimas en accidente como una cadena compuesta de varios eslabones, entre los que se encuentran:": "common-3-5",
  "entre las ventajas que presenta realizar una conducción económica se encuentra:": "common-1-3",
  "¿cuál de los siguientes estilos de conducción es inadecuado para el ahorro de carburante?": "common-1-3",
  "para que la pena impuesta por una acción de tráfico llegue a ser la privación de libertad, la acción debe ser:": "goods-2-2",
  "según la normativa estatal, ¿qué caracteriza a los itinerarios de interés general?": "goods-2-2",
  "¿qué objetivo tienen los primeros auxilios?": "common-3-5",
  "un alumno de un curso cap será excluido del mismo cuando deje de asistir a:": "common-2-1",
  "(reserva 20º) ¿qué se debe hacer ante una señal de stop?": "common-1-3bis",
  "¿qué son las enfermedades profesionales?": "common-3-3",
  "¿a quién causan un perjuicio económico los accidentes laborales?": "common-3-1",
  "en un sistema de frenado neumático, al pisar el pedal de freno se actúa sobre:": "common-1-2",
  "la cantidad de trabajo que puede proporcionar un motor por unidad de tiempo es:": "common-1-1",
  "¿qué sistema registra el consumo de combustible para su posterior análisis por la empresa?": "common-3-6",
  "el tipo de caja de velocidades que monte un automóvil, ¿puede influir en el consumo de carburante?": "common-1-3",
  "¿qué son los pares de las ruedas y pares de inercia?": "common-1-1",
  "las cooperativas de trabajo asociado pueden tener trabajadores asalariados, que no sean socios, siempre que el número de horas de trabajo realizadas por ellos no supere el:": "goods-3-7",
  "¿cuáles son los mecanismos de que se compone el airbag?": "common-1-2",
  "¿cuál es el propósito principal de la declaración amistosa de accidentes?": "common-3-5",
  "entre las fuerzas que se oponen al movimiento de un camión, ¿qué dos efectos produce la resistencia del aire o fuerza aerodinámica?": "common-1-1",
  "¿qué caracteriza a las autovías, según la normativa estatal?": "common-1-3bis",
  "¿cuál es el objetivo principal del tacógrafo?": "common-2-1",
  "¿para cuántos viajes sirve cada cuaderno tir?": "goods-2-2",
  "el sistema de frenado abs (antiblock brake system) es un elemento de seguridad:": "common-1-2",
  "según la capacidad de enfriamiento, ¿cuántas clases de vehículos refrigerantes existen?": "goods-1-4",
  "¿es obligatorio un dispositivo indicador de velocidad en el tacógrafo analógico?": "common-2-1",
  "¿qué tipo de colisión suele tener lesiones más graves?": "common-1-3bis",
  "¿la fatiga y el sueño pueden incidir en el tiempo de reacción durante la conducción?": "common-3-4",
  "¿permite la normativa vigente establecer recargos en los peajes?": "goods-2-2",
  "el par máximo representa el máximo esfuerzo que se puede obtener:": "common-1-1",
  "¿a qué circunstancias, con repercusiones negativas sobre su salud, se encuentra sometido el conductor profesional?": "common-3-3",
  "¿qué hay que presentar, y en qué momento, en relación con unas mercancías que se introducen en territorio de la unión europea?": "goods-2-2",
  "los transportistas, respecto de las rutas procedentes de fuera del espacio schengen, están obligados a comunicar a las autoridades encargadas del control de entrada:": "goods-2-2",
  "durante un transporte de mercancías peligrosas, ¿qué documento debe llevarse a bordo?": "goods-2-2",
  "cuando el conductor de un camión frene en una pendiente descendente, ¿qué ocurrirá con la mercancía?": "goods-1-4",
  "en el caso de transportes efectuados en régimen de tránsito de la unión, ¿cómo se denomina el documento expedido para acompañar a las mercancías?": "goods-2-2",
  "los vehículos que se adscriban a una autorización de transporte público de mercancías deben estar a disposición del titular:": "goods-2-2",
  "se presume que existe acuerdo de sometimiento a las juntas arbitrales del transporte cuando la cuantía de la controversia no excede de:": "goods-2-2",
  "en base al derecho español, ¿puede decirse que el contrato de transporte tiene carácter consensual?": "goods-2-2",
  "¿cuál debe de ser la actuación del conductor de una empresa de transportes en las inspecciones llevadas a cabo en carretera?": "goods-2-2",
  "¿cuál es la manipulación de cargas menos peligrosa?": "common-3-3",
  "los transportes efectuados mediante vehículos que se sometan a pruebas en carretera y vehículos nuevos o transformados que aún no se hayan puesto en circulación:": "goods-2-2",
  "en el caso de transporte privado complementario de mercancías:": "goods-2-2",
  "¿se podrá facturar a los clientes dicho transporte de modo independiente cuando se realice un transporte privado complementario de mercancías?": "goods-2-2",
  "desde que el vehículo ha sido puesto a disposición del cargador, ¿en qué plazo se efectuará la carga?": "goods-2-2",
  "¿cuál de las siguientes piezas no forma parte del cuerpo principal del motor?": "common-1-1",
  "¿cuál es el límite de alcohol?": "common-3-4",
  "¿qué debe hacer constar el conductor en una nueva hoja de registro o disco-diagrama antes de insertarla?": "common-2-1",
  "cuando los neumáticos de un camión no son capaces de evacuar toda el agua que se encuentran y pierden contacto con el suelo, se habla de:": "common-1-3bis",
  "¿qué es aconsejable en caso de que el vehículo derrape como consecuencia de exceso de presión sobre el pedal del freno?": "common-1-3bis",
  "¿con qué elemento de seguridad activa del vehículo está relacionado el tcs, traction control system?": "common-1-2",
  "en las estadísticas sobre accidentes de tráfico, el índice de letalidad pone en relación:": "common-1-3bis",
  "para que se produzca fuego, ¿qué se debe conjugar siempre en la proporción adecuada?": "common-3-5",
  "si la resultante de las fuerzas de frenado y de guiado lateral se encuentra dentro del círculo de kamm, el camión:": "common-1-3bis",
  "¿por qué se produce una aparente estimulación con el consumo de alcohol a niveles bajos?": "common-3-4",
  "la utilización adecuada de la caja de velocidades:": "common-1-1",
  "¿cuándo está especialmente aconsejado que el conductor evacúe el vehículo?": "common-3-5",
  "¿qué es recomendable en zonas inundadas por lluvia?": "common-1-3bis",
  "el proceso de conducción:": "common-1-3bis",
  "¿qué validez tiene la homologación que la administración debe otorgar a los cursos de formación cap para poder ser impartidos?": "common-2-1",
  "cuando la presión del neumático es superior a la recomendada:": "common-1-3bis",
  "¿es obligatorio el tacógrafo en todos los camiones?": "common-2-1",
  "¿se pueden recuperar puntos del permiso de conducir que se hayan perdido, si se cursa la formación cap?": "common-2-1",
  "¿puede ser conveniente saltarse una o varias velocidades durante la conducción de un camión?": "common-1-1",
  "¿qué circunstancias pueden ser un indicio de posibilidad de derrape del vehículo?": "common-1-3bis",
  "el exceso de 45 minutos sobre los tiempos máximos de conducción diarios, ¿qué tipo de infracción se considera?": "common-2-1",
  "el sistema pcs (pre-collision system) es un elemento de seguridad:": "common-1-2",
  "un conductor que realiza un descanso semanal reducido de 21 horas, ¿comete alguna infracción?": "common-2-1",
  "¿qué es el aquaplaning?": "common-1-3bis",
  "(reserva 10º) ¿qué son los indicadores de fatiga?": "common-3-4",
  "¿cuántos puntos se pierden en el permiso de conducir por minorar los tiempos de descanso obligatorios para un conductor en un porcentaje comprendido entre el 25 y el 50%?": "common-2-1",
  "¿qué podemos decir de la cooperativa de trabajo asociado?": "goods-3-7",
  "¿qué se entiende por factor de riesgo?": "common-3-1",
  "¿qué es una vía interurbana?": "common-1-3bis",
  "¿en qué supuestos, durante su plazo de validez administrativa, podrá ser retirada o suspendida la tarjeta de tacógrafo de conductor?": "common-2-1",
  "¿qué función tiene el sistema de ayuda a la conducción denominado pcw?": "common-1-2",
  "en presencia de un accidente de tráfico, al solicitar ayuda especializada:": "common-3-5",
  "¿qué requisitos deben cumplir los extranjeros que quieran entrar en españa?": "goods-2-2",
  "¿cómo se puede describir el embalaje?": "goods-1-4",
  "en función de por dónde se circule, se recomiendan unas técnicas indicadas para optimizar el consumo de carburante. ¿qué se recomienda en pendientes descendentes?": "common-1-3",
  "la calzada es la zona de la carretera destinada a la circulación de vehículos y se compone de:": "common-1-3bis",
  "el tipo de embrague que monte un automóvil, ¿puede influir en el consumo de carburante?": "common-1-3",
  "¿cuándo se incurre en la infracción consistente en carencia significativa de datos registrados en el tacógrafo?": "common-2-1",
  "en una caja de cambios, ¿qué tipo de dispositivo son los retardadores?": "common-1-2",
  "¿cómo influye la lluvia en la conducción?": "common-1-3bis",
  "según el acuerdo atp, ¿qué es un vehículo identificado con las letras frf?": "goods-2-2",
  "para realizar transporte internacional de mercancías que exija contar con licencia comunitaria, es necesario que las empresas dispongan, como mínimo, de:": "goods-2-2",
  "en la unión europea están liberalizados los transportes internacionales de mercancías realizados con vehículos cuyo peso de carga total autorizado no sea superior a:": "goods-2-2",
  "¿qué tipo de productos se pueden utilizar para limpiar un vehículo dedicado al transporte de alimentos?": "goods-1-4",
  "un documento de identificación con fotografía por cada miembro de la tripulación, ¿es un documento obligatorio que debe llevarse a bordo del vehículo durante un transporte de mercancías peligrosas?": "goods-2-2",
  "para iniciar un transporte tir, ¿qué se debe presentar en la aduana de partida?": "goods-2-2",
  "la sobrecarga del eje de un camión": "goods-1-4",
  "el tipo de esfuerzo requerido para el manejo de la carga influye en el nivel de riesgo. así, es más segura la manipulación que exija:": "common-3-3",
  "la declaración previa a la salida de mercancías del territorio aduanero de la unión se hace mediante una:": "goods-2-2",
  "los datos que registra un tacógrafo analógico son recogidos en unos documentos llamados:": "common-2-1",
  "¿cuál de las siguientes no es una ventaja de los líquidos refrigerantes utilizados corrientemente?": "common-3-6",
  "¿dónde debe solicitar el conductor su tarjeta para tacógrafo digital?": "common-2-1",
  "¿en qué zona del cuentarrevoluciones existe un equilibrio entre la cantidad de carburante que se inyecta y la cantidad de aire que hay en el cilindro, aprovechándose en mayor medida el carburante inyectado?": "common-1-1",
  "¿cuándo deben colocar el disco-diagrama u hoja de registro los conductores?": "common-2-1",
  "¿qué regla se debe seguir para garantizar una conducción más segura?": "common-1-3bis",
  "¿qué actuación es correcta para optimizar el consumo de carburante?": "common-1-3",
  "¿qué actuación es inadecuada para reducir el consumo de carburante de un automóvil?": "common-1-3",
  "la sustitución del aceite lubricante...": "common-3-6",
  "¿qué es el ebs?": "common-1-2",
  "¿cuál es el plazo de prescripción de las infracciones graves de las normas relativas a los tiempos de conducción y descanso?": "common-2-1",
  "¿ante una señal de stop qué se hace?": "common-1-3bis",
  "¿qué sirven las luces de posición?": "common-1-2",
  "¿qué deberá hacer el conductor en caso de que se le imponga una sanción por incumplimiento de las normas sobre tiempos de conducción y descanso?": "common-2-1",
  "(reserva 15º) ¿cuál es el límite de velocidad en autovías para camiones?": "common-1-3bis",
  "¿cuál no es una actuación que pueden efectuar los agentes de la autoridad en los controles en carretera?": "common-2-1",
  "¿el consumo de alcohol puede provocar alteración en el tiempo de reacción y en la atención?": "common-3-4",
  "el mayor o menor consumo de carburante de un vehículo pesado depende de varios factores, entre otros:": "common-1-3",
  "¿qué dos efectos tiene la resistencia del aire sobre el movimiento del camión?": "common-1-3",
  "los vehículos exentos del uso del tacógrafo por aplicación de la normativa española, ¿tienen que usarlo en los recorridos en vacío que necesariamente realicen antes o después del servicio en el que están exentos?": "common-2-1",
  "en los vehículos de temperatura controlada, ¿dónde se colocarán las marcas de identificación y la fecha de expiración validez del certificado atp del vehículo?": "goods-2-2",
  "¿qué puede producir un derrape del vehículo?": "common-1-3bis",
  "(reserva 14º) ¿qué es una vía interurbana?": "common-1-3bis",
  "¿pueden las cooperativas de trabajo asociado tener trabajadores asalariados que no sean socios?": "goods-3-7",
  "el mal estado del filtro de aceite:": "common-3-6",
  "el sistema de alerta de colisión frontal se conoce también por las siglas:": "common-1-2",
  "uno de los elementos del sistema neumático de frenos es...": "common-1-2",
  "¿qué factor puede hacer variar el grado de rozamiento?": "common-1-3bis",
  "como medida de ahorro de carburante, ¿qué actuación, de las que se citan, es correcta?": "common-1-3",
  "¿para qué sirve el sistema abs?": "common-1-2",
  "(reserva 8º) ¿es obligatorio el uso de cinturón de seguridad en autobuses con cinturón instalado?": "common-1-2",
  "¿qué requerimientos suelen ir asociados a la conducción profesional?": "common-2-1",
  "¿cuál de los siguientes países forma parte del espacio schengen?": "goods-2-2",
  "¿qué muestra la curva de potencia a plena carga?": "common-1-1",
  "si en un contrato de transporte se ha pactado el día, pero no la hora, bastará con que el vehículo esté a disposición del cargador antes de las:": "goods-2-2",
  "las agencias de transporte de mercancías y los almacenistas-distribuidores contratarán:": "goods-2-2",
  "¿con qué antelación debe comunicarse al centro de gestión de tráfico de la zona afectada la circulación de un transporte de mercancías peligrosas por una vía no incluida en la rimp?": "goods-2-2",
  "¿cuál es el número mínimo de vehículos exigido para obtener autorización de transporte público de mercancías que habilite a efectuar transportes con vehículos de masa máxima autorizada superior a 3,5 toneladas?": "goods-2-2",
  "una buena estiba requiere que la carga sea colocada:": "goods-1-4",
  "están exentos de autorización administrativa los transportes de mercancías de carácter privado complementario realizados en vehículos de:": "goods-2-2",
  "si la carga está mal estibada, ¿qué puede provocar?": "goods-1-4",
  "en un contrato de transporte sujeto al convenio cmr, el transportista responde de los daños sufridos por la mercancía:": "goods-2-2",
  "¿qué dato no necesita el conductor para efectuar un transporte de mercancías?": "goods-2-2",
  "¿con qué se pueden mecanizar los procesos de manipulación de cargas?": "goods-1-4",
  "¿cómo se deben utilizar las cuñas para fijar la carga?": "goods-1-4",
  "¿qué comportamiento es aconsejable para los conductores?": "common-3-6",
  "103 (reserva 3º). ¿cuáles de los siguientes estados forman parte del espacio schengen?": "goods-2-2",
  "en una sociedad laboral de 30 socios, el número de horas/año trabajadas por los trabajadores contratados por tiempo indefinido que no sean socios no podrá ser superior al:": "goods-3-7",
  "¿la puesta a punto del vehículo repercute significativamente en el ahorro de consumo de carburante?": "common-1-3",
  "las autorizaciones bilaterales": "goods-2-2",
  "de acuerdo con el reglamento (ce) 561/2006, ¿a qué concepto se refiere la expresión \"el período de tiempo comprendido entre las 00.00 del lunes y las 24.00 del domingo\"?": "common-2-1",
  "¿qué altura debe tener un asiento para los trabajadores que trabajen sentados?": "common-3-3",
  "con un consumo igual, el nivel de alcohol en sangre que se puede alcanzar es más elevado:": "common-3-4",
  "¿qué significa \"masa máxima autorizada\"?": "goods-1-4",
  "¿se pueden acumular en una misma persona las diferentes modalidades del estatuto de operador económico autorizado?": "goods-2-2",
  "¿a qué distancia se colocará la señalización vertical o cartel informativo sobre el significado de la marca vial denominada galón?": "common-1-3bis",
  "en el puesto de conducción, la temperatura es un factor a tener en cuenta:": "common-3-3",
  "¿cuál es la marca de identificación de un vehículo frigorífico normal de la clase d?": "goods-1-4",
  "¿qué función tiene, entre otras, el sistema de ayuda a la conducción identificado con las letras acc?": "common-1-2",
  "el exceso superior a dos horas sobre los tiempos máximos de conducción diaria, ¿qué tipo de infracción se considera?": "common-2-1",
  "¿en base a qué elige el conductor, principalmente, su nivel de riesgo aceptado?": "common-1-3bis",
  "¿de qué informan a los conductores las marcas viales denominadas galón, colocadas en determinados tramos de una carretera?": "common-1-3bis",
  "¿qué fuerza interviene en el movimiento de un camión?": "common-1-1",
  "¿cuál de las siguientes infracciones no es motivo de inmovilización del vehículo?": "common-1-3bis",
  "la no presentación a los agentes de control de todos los discos utilizados por un conductor en los 56 días anteriores, ¿supone cometer alguna infracción?": "common-2-1",
  "sobre la aerodinámica de un vehículo, se debe saber que:": "common-1-3",
  "¿cómo debe ser el alumbrado nocturno?": "common-1-3bis",
  "la evaluación correcta de una situación de emergencia permite:": "common-3-5",
  "¿cuál es el número mínimo de vehículos requerido para obtener autorización de transporte privado complementario de mercancías?": "goods-2-2",
  "¿puede una empresa ya autorizada para transporte público de mercancías ampliar el número de vehículos adscritos a su autorización de transporte?": "goods-2-2",
  "¿cuál de las siguientes se considera mercancía de la unión a efectos aduaneros?": "goods-2-2",
  "en un contrato de transporte sujeto al convenio cmr, el transportista no debe responder de los daños sufridos por la mercancía cuando pruebe que estos derivan:": "goods-2-2",
  "¿cuál de las siguientes se considera mercancía no perteneciente a la unión a efectos aduaneros?": "goods-2-2",
  "¿en qué casos prevé la normativa que las juntas arbitrales del transporte acuerden el depósito de mercancías?": "goods-2-2",
  "¿qué se entiende por transporte intermodal?": "goods-2-2",
  "¿cuáles son las funciones propias del jefe de tráfico de una empresa de transporte de mercancías por carretera?": "goods-3-7",
  "en un contrato de transporte sujeto al convenio cmr que es ejecutado por varios transportistas de modo sucesivo, ¿contra quién se puede dirigir una reclamación por pérdida de la mercancía?": "goods-2-2",
  "según las condiciones generales de contratación, el retorno de los soportes aportados por el cargador:": "goods-2-2",
  "el convenio cmr se aplicará a los transportes efectuados:": "goods-2-2",
  "¿qué restricción pueden tener las autorizaciones cemt?": "goods-2-2",
  "¿cuándo podrá el titular de una autorización de transporte público de mercancías intermediar en la contratación de transporte?": "goods-2-2",
  "¿una cooperativa de trabajo asociado puede tener trabajadores asalariados que no sean socios?": "goods-3-7",
  "(reserva 31º) los conductores deben someterse a pruebas de alcoholemia:": "common-3-4",
  "¿cuándo deben usarse las pinzas en el cinturón de seguridad?": "common-1-2",
  "103 (reserva 3º). el mayor o menor consumo de carburante de un vehículo pesado depende de varios factores, entre otros:": "common-1-3",
  "la energía acumulada por un camión en movimiento depende:": "common-1-3",
  "en relación con la cualificación inicial y la formación continua de los conductores, ¿en qué registro se anota la expedición del cap?": "common-2-1",
  "¿cómo actúa el sistema ebs?": "common-1-2",
  "a altas revoluciones, la cantidad de combustible que se inyecta es mucha, pero no hay suficiente aire para que pueda mezclarse y quemarse. ¿por qué es poca la cantidad de aire?": "common-1-1",
  "si un vehículo mixto adaptable ostenta la señal v-15, ¿podrá utilizar un carril para vao?": "common-1-3bis",
  "102 (reserva 2º). ¿cuál es el ámbito de aplicación del espacio schengen?": "goods-2-2",
  "de las que se citan, ¿cuál constituye una resistencia al avance del camión?": "common-1-3",
  "¿en qué lugares se puede efectuar una inmovilización a un vehículo?": "common-1-3bis",
  "un vehículo frigorífico de clase c debe conseguir bajar la temperatura y mantenerla después, con una temperatura exterior media de +30 °c, como máximo a:": "goods-1-4",
  "de los siguientes factores de los que depende la potencia de un motor, ¿cuál es el que más influye en su valor?": "common-1-1",
  "el consumo de carburante de un vehículo pesado puede ser mayor de lo normal dependiendo:": "common-1-3",
  "¿cuál de los siguientes vehículos se ve con más frecuencia implicado en accidentes de tráfico?": "common-1-3bis",
  "la cantidad de carburante que gasta un motor en relación a la potencia desarrollada en un tiempo determinado se llama:": "common-1-3",
  "un exceso de conducción considerado como leve, ¿puede ser motivo de inmovilización del vehículo?": "common-2-1",
  "a efectos de la aplicación de la normativa de extranjería, el llamado \"espacio schengen\" comprende países pertenecientes a:": "common-3-2",
  "una conducción semanal de 65 horas, ¿qué tipo de infracción se considera?": "common-2-1",
  "¿qué se puede observar en el círculo de kamm?": "common-1-3bis",
  "conducir utilizando la relación de marchas más alta posible, dependiendo de la velocidad a la que se circule, tiene como ventaja:": "common-1-3",
  "en camiones de caja abierta, ¿dónde debe situarse la carga para reducir la resistencia del aire?": "common-1-3",
  "los transportes realizados en vehículos exclusivamente dedicados a la prestación de servicios de alcantarillado:": "goods-2-2",
  "en aquellos camiones que poseen la caja de carga abierta, o en autobuses de dos pisos con el piso superior descubierto, el consumo de carburante:": "common-1-3",
  "del documento de control administrativo del transporte se emiten dos ejemplares cuyos destinatarios son:": "goods-2-2",
  "dentro de los sistemas de transporte inteligente se encuentran los denominados dai, ¿cuál es su funcionalidad?": "common-1-3bis",
  "si, por causa de un accidente o avería, el vehículo o su carga obstaculizan la calzada, ¿cuál será la primera actuación que deberá realizar el conductor?": "common-3-5",
  "¿es función del conductor de un vehículo de transporte de mercancías cumplimentar algún tipo de documentación?": "goods-2-2",
  "¿comete delito un conductor que se niegue a someterse a pruebas de alcoholemia?": "common-3-4",
  "en el supuesto de que las autoridades ordenen la inmovilización de un vehículo por falta de descanso del conductor, ¿a quién corresponde la responsabilidad por la custodia del vehículo?": "common-2-1",
  "¿cuál es el espacio de trabajo específico de los conductores?": "common-3-3",
  "¿qué relación general hay entre la resistencia aerodinámica y la velocidad?": "common-1-3",
  "¿cuál debe ser la base para la imposición de peajes en españa?": "goods-3-7",
  "¿cómo se denominan los accidentes ocurridos en los desplazamientos de ida y vuelta al lugar de trabajo?": "common-3-1",
  "¿cuál es el plazo de prescripción de las sanciones por infracciones muy graves de las normas relativas a los tiempos de conducción y descanso?": "common-2-1",
  "¿cómo actúa el sistema de ayuda a la conducción denominado tsr?": "common-1-2",
  "¿qué lesión medular implica la pérdida de funciones motoras en todas las extremidades y el tronco?": "common-3-5",
  "el chasis deformable es un elemento de seguridad:": "common-1-2",
  "¿qué se entiende por control fronterizo en la regulación del espacio schengen?": "goods-2-2",
  "en caso de colisión o alcance, los reposacabezas evitan o disminuyen considerablemente:": "common-1-2",
  "es un elemento imprescindible de un sistema de prevención:": "common-3-1",
  "si la calzada está cubierta de hielo y se pisa fuertemente el pedal del freno, el sistema antibloqueo de frenos (abs), ¿evita el bloqueo de la rueda?": "common-1-2",
  "¿cuál de los siguientes es el tipo más frecuente de accidente de tráfico en el que se ven implicados camiones o autobuses?": "common-1-3bis",
  "en un vehículo dotado de abs, ¿cómo se debe proceder ante una frenada de emergencia?": "common-1-2",
  "¿qué función realizan los pares de viraje?": "common-1-1",
  "¿cómo debe efectuarse el intercambio de información entre las autoridades aduaneras y los operadores económicos?": "goods-2-2",
  "¿cuál sería una medida de precaución para evitar atropellos?": "common-1-3bis",
  "¿cuál de los siguientes vehículos se ve con menos frecuencia implicado en accidentes de tráfico?": "common-1-3bis",
  "¿el tacógrafo digital puede emitir señales de advertencia al conductor?": "common-2-1",
  "¿qué actuación es inadecuada como medida de ahorro de carburante?": "common-1-3",
  "los transportes de mercancías realizados en vehículos de menos de tres ruedas:": "goods-2-2",
  "respecto de las bolsas de carga, ¿cuál de estas afirmaciones no es correcta?": "goods-1-4",
  "101 (reserva 1º). en el transporte internacional, ¿a qué se denomina operaciones triangulares?": "goods-2-2",
  "¿es necesario que los miembros de las juntas arbitrales del transporte tengan alguna titulación?": "goods-2-2",
  "en caso de producirse alguna incidencia durante un transporte efectuado en régimen de tránsito de la unión, ¿qué debe hacer el transportista por lo que se refiere a la normativa aduanera?": "goods-2-2",
  "si, como consecuencia de una inspección de transporte en carretera, hay que proceder al traslado obligatorio del vehículo:": "goods-2-2",
  "según las condiciones generales de contratación, ¿qué puede hacer un transportista de mercancías peligrosas si no ha sido informado de su peligrosidad?": "goods-2-2",
  "¿qué requisito es necesario para que la declaración amistosa de accidente sea válida?": "common-3-5",
  "en un control en carretera, ¿está obligado el conductor a colaborar con el personal que realiza la inspección?": "goods-2-2",
  "la normativa española sobre ordenación del tiempo de trabajo de los conductores autónomos:": "common-2-1",
  "cuando los neumáticos no son capaces de evacuar toda el agua que encuentran y pierden contacto con el suelo, deslizándose sobre éste, se produce:": "common-1-3bis",
  "al prestar ayuda en un accidente de circulación, ¿cuál debe ser el segundo objetivo de la intervención?": "common-3-5",
  "(reserva 16º) ¿qué documentos son necesarios para la circulación de un vehículo?": "common-2-1",
  "el tacógrafo analógico registra datos acerca del conductor y del vehículo en:": "common-2-1",
  "¿qué tipo de señal es una señal circular roja?": "common-1-3bis",
  "¿qué es una señal de stop?": "common-1-3bis",
  "cuando la inclinación que alcanza el camión es la máxima posible o cercana a la máxima, se habla de:": "goods-1-4",
  "un fuego es:": "common-3-5",
  "si caen gotas de agua por el tubo de escape después de un arranque en frío, significa que...": "common-3-6",
  "el esp es un dispositivo que:": "common-1-2",
  "¿a qué se deben principalmente las pérdidas energéticas que se producen en la transmisión?": "common-1-1",
  "el cinturón de seguridad debe:": "common-1-2"
};
